<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class C11 extends Model
{
    use HasFactory;

    protected $table = 'c11';

    protected $fillable = [
        'establecimiento',
        'medico',
        'fconsulta',
        'hclin',
        'asegurado',
        'apellidosynombres',
        'sexo',
        'fnacimiento',
        'vihpreconsejeriam',
        'vihpreconsejeriaf',
        'vihprapidaembf',
        'vihprapidam',
        'vihprapidaf',
        'tbsintomaticosrm',
        'tbsintomaticosrf',
        'tbpbaarnuevosposm',
        'tbpbaarnuevosposf',
        'tbpbaarnuevosnegm',
        'tbpbaarnuevosnegf',
        'tbtbextrapnm',
        'tbtbextrapnf',
        'tbesqim',
        'tbesqif',
        'tbesqiim',
        'tbesqiif',
        'tbesqiiim',
        'tbesqiiif',
        'tbquimiprofilaxism5m',
        'tbquimiprofilaxism5f',
        'tbbaarposnuevoscuradosm',
        'tbbaarposnuevoscuradosf',
        'tbttopausibacilarinim',
        'tbttopausibacilarinif',
        'tbttomultibacilarinim',
        'tbttomultibacilarinif',
        'malariamuestrasvivaxm',
        'malariamuestrasvivaxf',
        'malariamuestrasfalciparumm',
        'malariamuestrasfalciparumf',
        'malariaconfirmadosvivaxm',
        'malariaconfirmadosvivaxf',
        'malariaconfirmadosfalciparumm',
        'malariaconfirmadosfalciparumf',
        'malariattovivaxm',
        'malariattovivaxf',
        'malariattofalciparumm',
        'malariattofalciparumf',
        'malariattosospechavivaxm',
        'malariattosospechavivaxf',
        'malariattosospechafalciparumm',
        'malariattosospechafalciparumf',
        'malariattoantes48hrsiniciosintomasvivaxm',
        'malariattoantes48hrsiniciosintomasvivaxf',
        'malariattoantes48hrsiniciosintomasfalciparumm',
        'malariattoantes48hrsiniciosintomasfalciparumf',
        'chagasttornam1ainiciadm',
        'chagasttornam1ainiciadf',
        'chagasttornam1aconcluidom',
        'chagasttornam1aconcluidof',
        'chagastto1am5ainiciadm',
        'chagastto1am5ainiciadf',
        'chagastto1am5aconcluidom',
        'chagastto1am5aconcluidof',
        'chagastto5am15ainiciadm',
        'chagastto5am15ainiciadf',
        'chagastto5am15aconcluidom',
        'chagastto5am15aconcluidof',
        'chagastto15amasiniciadm',
        'chagastto15amasiniciadf',
        'chagastto15amasconcluidom',
        'chagastto15amasconcluidof',
        'chagasttomujeresostpartoinf',
        'chagasttomujeresostpartoconf',
        'chagasviviendaseval',
        'chagasviviendasposi',
        'chagasviviendasroc',
        'vectoresviviendasevalentomol',
        'vectoresviviendasposi',
        'vectoresttoleishiniciadof',
        'vectoresttoleishiniciadom',
        'vectoresttoleishconclm',
        'vectoresttoleishconclf',
        'vectoresttoleishmucoinim',
        'vectoresttoleishmucoinif',
        'vectoresttoleishmucoconm',
        'vectoresttoleishmucoconf',
        'vectoresttoleishmucocutainim',
        'vectoresttoleishmucocutainif',
        'vectoresttoleishmucocutaconm',
        'vectoresttoleishmucocutaconf',
        'vectoresttoleishviscinim',
        'vectoresttoleishviscinif',
        'vectoresttoleishvisconm',
        'vectoresttoleishvisconf',
    ];
}
